### ISSUE TITLE
Extensions is broken in Brackets sprint 26

### ISSUE THREAD

**Issue by tvb** [theproducer/brackets-ftp#2]
When opening the extension setup window:

![screen shot 2013-06-13 at 14 53 52](https://f.cloud.github.com/assets/1263414/648347/53db20fc-d428-11e2-80f7-08e9e51a4bf6.png)

**Comment by pfhenley86** [comment]
Yeah I got the same thing.

**Comment by barbuslex** [comment]
Same problem

**Comment by Tusko** [comment]
+1
in Windows 8

**Comment by theproducer** [comment]
Should be fixed in the latest commit.
